---
title: "canada_wild_fires"
output: html_document
date: "2023-08-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("plotly")
# install.packages("DT")
# install.packages("reticulate")
# install.packages("pandas")
```


```{r}
# library(shiny)
# library(plotly)
# library(DT)
library(shinyWidgets)
```



```{r canada forest fires}
fireNumber <- read.csv(file="../data/Cleaned_Number_of_fires_by_month.csv", header=TRUE, sep=",")
fireArea <- read.csv("../data/Cleaned_Area_burned_by_month.csv", header=TRUE, sep=",")
fireLoss <- read.csv("../data/Cleaned_Property_losses.csv", header=TRUE, sep=",")
```


```{r}
unique_jurisdictions <- unique(c(fireNumber$Jurisdiction, fireArea$Jurisdiction, fireLoss$Jurisdiction))
```


```{r}
ui <- fluidPage(
   
   # Application title
   titlePanel("Canada Forest Fires Statistics"),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
         selectInput("choice", "Project Page", c("Home", "Fire Counts", "Burned Area (hectares)", "Property Losses")),
         
         conditionalPanel(
            condition = "input.choice == 'Fire Counts'",
            pickerInput("fire_number_year", "Year", choices = fireNumber$Year, selected = NULL, multiple = TRUE, options = list(`live-search` = TRUE)),
            pickerInput("fire_number_month", "Month", choices = fireNumber$Month, selected = NULL, multiple = TRUE, options = list(`live-search` = TRUE)),
            pickerInput("fire_number_jurisdiction", "Jurisdiction", choices = unique_jurisdictions, selected = NULL, multiple = TRUE, options = list(`live-search` = TRUE))
         ),
         
         conditionalPanel(
            condition = "input.choice == 'Burned Area (hectares)'",
            pickerInput("fire_area_year", "Year", choices = fireArea$Year, selected = NULL, multiple = TRUE, options = list(`live-search` = TRUE)),
            pickerInput("fire_area_month", "Month", choices = fireArea$Month, selected = NULL, multiple = TRUE, options = list(`live-search` = TRUE)),
            pickerInput("fire_area_jurisdiction", "Jurisdiction", choices = unique_jurisdictions, selected = NULL, multiple = TRUE, options = list(`live-search` = TRUE))
         ),
         
         conditionalPanel(
            condition = "input.choice == 'Property Losses'",
            pickerInput("fire_loss_year", "Year", choices = fireLoss$Year, selected = NULL, multiple = TRUE, options = list(`live-search` = TRUE)),
            pickerInput("fire_loss_jurisdiction", "Jurisdiction", choices = unique_jurisdictions, selected = NULL, multiple = TRUE, options = list(`live-search` = TRUE))
         )
         
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
         uiOutput("main_content")
      )
   )
)

```

```{r}
# Define server logic required to draw a histogram
server <- function(input, output) {
   
   output$main_content <- renderUI({
      if(input$choice == "Home"){
         tagList(
            titlePanel("Home Page"),
            textOutput("Home_Content")
         )
      }
      else if(input$choice == "Fire Counts"){
         tagList(
            plotlyOutput("Fire_Counts"),
            dataTableOutput("Fire_Counts_Table")
         )
      }
      else if(input$choice == "Burned Area (hectares)"){
         tagList(
            plotlyOutput("Burned_Area"),
            dataTableOutput("Burned_Area_Table")
         )
      }
      else if(input$choice == "Property Losses"){
         tagList(
            plotlyOutput("Property_Losses"),
            dataTableOutput("Property_Losses_Table")
         )
      }
   })
   
   output$Fire_Counts <- renderPlotly({
      # Filter and plot code for "Fire Counts" goes here...
   })
   
   output$Fire_Counts_Table <- renderDataTable({
      # Filter and table creation code for "Fire Counts" goes here...
   })
   
   output$Burned_Area <- renderPlotly({
      # Filter and plot code for "Burned Area" goes here...
   })
   
   output$Burned_Area_Table <- renderDataTable({
      # Filter and table creation code for "Burned Area" goes here...
   })
   
   output$Property_Losses <- renderPlotly({
      # Filter and plot code for "Property Losses" goes here...
   })
   
   output$Property_Losses_Table <- renderDataTable({
      # Filter and table creation code for "Property Losses" goes here...
   })
   
   output$Home_Content <- renderText({
      # Home content code goes here...
   })
   
}
```


```{r}
shinyApp(ui = ui, server = server)
```

